### ISSUE TITLE
Missing files in the project

### ISSUE THREAD

**Issue by iltercengiz** [objcio/swift-talk-app-swiftui#1]
Apparently some classes are not copied to the project directory. 😅 
Session.swift and Account.swift to be exact.
```
error: Build input files cannot be found: '/System/Volumes/Data/Users/chris/Downloads/swift-talk-app-swiftui/Session.swift', '/System/Volumes/Data/Users/chris/Downloads/swift-talk-app-swiftui/SwiftTalk/AuthenticationHelpers.swift', '/System/Volumes/Data/Users/chris/Downloads/swift-talk-app-swiftui/Account.swift' (in target 'SwiftTalk' from project 'SwiftTalk')
```

**Comment by liorazi** [comment]
Fixed on latest merge

**Comment by chriseidhof** [comment]
I think it was an Xcode issue... sorry about that!

**Comment by marcoscurvello** [comment]
I just encountered the exact same error downloading the repo. What's strange is, if I clone it on my machine, files have the correct reference path and it builds fine.
